/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and start a session */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Rate limited per IP. After 5 failed attempts for the same email within 15 minutes, further attempts return 429 until the window expires.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and issue a new access token
         * @description The refresh token is single-use. Presenting one that was already rotated revokes every session in its family (reuse detection). Rate limited per IP, but requests without a refresh_token cookie are rejected with 401 before the rate limit, so anonymous visitors do not use up the login / signup limit.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the refresh token and clear auth cookies */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List movies
         * @description Paginated. Ties in the sort field are broken by id, so pages are stable.
         */
        get: operations["listMovies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a movie */
        get: operations["getMovie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all genres */
        get: operations["listGenres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the signed-in user's watchlist
         * @description Newest first. Each item includes the full movie.
         */
        get: operations["listWatchlist"];
        put?: never;
        /** Add a movie to the watchlist */
        post: operations["addToWatchlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the signed-in user's watchlist as ids
         * @description Every item, unpaginated, with only `id`, `movieId` and `status`. Meant for the client to mark which movies are already in the watchlist.
         */
        get: operations["listWatchlistIds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an item from the watchlist */
        delete: operations["removeFromWatchlist"];
        options?: never;
        head?: never;
        /** Update status, rating or notes */
        patch: operations["updateWatchlistItem"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SignupRequest: {
            /** @example Demo User */
            name: string;
            /**
             * @description Trimmed and lowercased before use
             * @example demo@example.com
             */
            email: string;
            /**
             * @description 8 characters to 72 bytes (UTF-8), the bcrypt input limit
             * @example correct-horse-battery
             */
            password: string;
        };
        LoginRequest: {
            /**
             * @description Trimmed and lowercased before use
             * @example demo@example.com
             */
            email: string;
            /** @example correct-horse-battery */
            password: string;
        };
        AddToWatchlistRequest: {
            /** Format: uuid */
            movieId: string;
            /** @enum {string} */
            status?: "PLANNED" | "WATCHING" | "COMPLETED" | "DROPPED";
            /** @example 8 */
            rating?: number;
            /** @example Rewatch with friends */
            notes?: string;
        };
        /** @description At least one field is required */
        UpdateWatchlistItemRequest: {
            /** @enum {string} */
            status?: "PLANNED" | "WATCHING" | "COMPLETED" | "DROPPED";
            /** @example 8 */
            rating?: number;
            /** @example Rewatch with friends */
            notes?: string;
        };
        ErrorResponse: {
            error: {
                /**
                 * @description Stable, machine-readable error code
                 * @example VALIDATION_ERROR
                 */
                code: string;
                /** @example Request validation failed */
                message: string;
                /** @description Only present on VALIDATION_ERROR */
                details?: {
                    /** @enum {string} */
                    location?: "params" | "query" | "body";
                    /** @example releaseYear */
                    path: string;
                    /** @example Too small: expected number to be >=1888 */
                    message: string;
                }[];
            };
        };
        /** @description Tokens are only sent as HttpOnly cookies, never in the body */
        Session: {
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** @example Demo User */
            name: string;
            /**
             * Format: email
             * @example demo@example.com
             */
            email: string;
        };
        Movie: {
            /** Format: uuid */
            id: string;
            /** @example The Silent Horizon */
            title: string;
            /** @example A lone astronaut drifts toward an uncharted signal at the edge of the solar system. */
            overview: string | null;
            /** @example 2019 */
            releaseYear: number;
            /** @example https://picsum.photos/seed/silent-horizon/400/600 */
            posterUrl: string | null;
            /** Format: date-time */
            createdAt: string;
            /** @description Sorted by name */
            genres: components["schemas"]["Genre"][];
        };
        Genre: {
            /** Format: uuid */
            id: string;
            /** @example Sci-Fi */
            name: string;
        };
        PaginationMeta: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 42 */
            total: number;
            /** @example 3 */
            totalPages: number;
        };
        WatchlistItemWithMovie: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            movieId: string;
            /** @enum {string} */
            status: "PLANNED" | "WATCHING" | "COMPLETED" | "DROPPED";
            /** @example 8 */
            rating: number | null;
            /** @example Rewatch with friends */
            notes: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            movie: components["schemas"]["Movie"];
        };
        WatchlistItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            movieId: string;
            /** @enum {string} */
            status: "PLANNED" | "WATCHING" | "COMPLETED" | "DROPPED";
            /** @example 8 */
            rating: number | null;
            /** @example Rewatch with friends */
            notes: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WatchlistId: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            movieId: string;
            /** @enum {string} */
            status: "PLANNED" | "WATCHING" | "COMPLETED" | "DROPPED";
        };
    };
    responses: {
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                /** @description Seconds to wait before retrying */
                "Retry-After": string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description `VALIDATION_ERROR` (see `details`) or `INVALID_JSON` (malformed body) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing, invalid or expired credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The resource does not exist, or it belongs to another user (never 403, to avoid leaking existence) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @constant */
                            status: "ok";
                        };
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Account created and signed in */
            201: {
                headers: {
                    /** @description `access_token` (Path=/api) and `refresh_token` (Path=/api/auth), both HttpOnly and SameSite=Strict */
                    "Set-Cookie": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Session"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    /** @description `access_token` (Path=/api) and `refresh_token` (Path=/api/auth), both HttpOnly and SameSite=Strict */
                    "Set-Cookie": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Session"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Set by login / signup / refresh. Path=/api/auth, HttpOnly, SameSite=Strict */
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description New tokens issued */
            200: {
                headers: {
                    /** @description `access_token` (Path=/api) and `refresh_token` (Path=/api/auth), both HttpOnly and SameSite=Strict */
                    "Set-Cookie": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Session"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Set by login / signup / refresh. Path=/api/auth, HttpOnly, SameSite=Strict */
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Signed out (also returned when there was no session) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listMovies: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Case-insensitive substring match on title */
                search?: string;
                /** @description Genre name, case-insensitive exact match */
                genre?: string;
                /** @description Release year */
                year?: number;
                sort?: "title" | "releaseYear" | "createdAt";
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of movies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Movie"][];
                        meta: components["schemas"]["PaginationMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getMovie: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The movie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Movie"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listGenres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All genres, sorted by name */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Genre"][];
                    };
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    listWatchlist: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                status?: "PLANNED" | "WATCHING" | "COMPLETED" | "DROPPED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of watchlist items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WatchlistItemWithMovie"][];
                        meta: components["schemas"]["PaginationMeta"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    addToWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToWatchlistRequest"];
            };
        };
        responses: {
            /** @description Added. `status` defaults to PLANNED */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WatchlistItem"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listWatchlistIds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All of the user's items, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WatchlistId"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    removeFromWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    updateWatchlistItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWatchlistItemRequest"];
            };
        };
        responses: {
            /** @description Item updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["WatchlistItem"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
